# 03 — Feature Engineering untuk Data Game

Latihan ini membuat fitur sederhana dari data katalog game. Kita belum membangun model machine learning; fokusnya menyiapkan kolom agar lebih mudah dianalisis.

In [1]:
from pathlib import Path
import pandas as pd

PROJECT_DIR = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()
games = pd.read_csv(PROJECT_DIR / 'data' / 'games_eda.csv')
games.head()

,game_id,title,genre,platform,release_year,studio,rating,price_usd,sales_millions,review_count
0,1,Wild Voyage 01,Strategy,PlayStation,2017,Northstar Studio,6.1,14.99,1.05,1357
1,2,Amber Islands 02,Strategy,Switch,2025,Blue Comet,6.4,14.99,2.51,15922
2,3,Amber Frontier 03,Puzzle,Xbox,2019,Orbit Works,9.1,4.99,6.27,10055
3,4,Cosmic Legends 04,Adventure,Xbox,2016,Maple Byte,8.3,61.99,2.10,3181
4,5,Frost Racers 05,Strategy,Xbox,2020,Orbit Works,5.9,9.99,3.10,6481

## 1. Membuat fitur umur game

In [2]:
current_year = 2026
games['game_age'] = current_year - games['release_year']
games[['title','release_year','game_age']].head(10)

                 title  release_year  game_age
0       Wild Voyage 01          2017         9
1     Amber Islands 02          2025         1
2    Amber Frontier 03          2019         7
3    Cosmic Legends 04          2016        10
4      Frost Racers 05          2020         6
5    Crystal Voyage 06          2021         5
6   Forgotten Realm 07          2023         3
7   Solar Labyrinth 08          2022         4
8  Golden Labyrinth 09          2016        10
9     Frost Academy 10          2023         3

## 2. Mengelompokkan rating

In [3]:
def rating_category(rating):
    if rating >= 8:
        return 'High'
    elif rating >= 6:
        return 'Medium'
    return 'Low'

games['rating_category'] = games['rating'].apply(rating_category)
display(games[['title','rating','rating_category']].head(10))
print(games['rating_category'].value_counts())

                 title  rating rating_category
0       Wild Voyage 01     6.1          Medium
1     Amber Islands 02     6.4          Medium
2    Amber Frontier 03     9.1            High
3    Cosmic Legends 04     8.3            High
4      Frost Racers 05     5.9             Low
5    Crystal Voyage 06     5.9             Low
6   Forgotten Realm 07     4.8             Low
7   Solar Labyrinth 08     6.5          Medium
8  Golden Labyrinth 09     7.4          Medium
9     Frost Academy 10     8.6            High

rating_category
Medium    48
High      20
Low       12
Name: count, dtype: int64

## 3. Encoding kategori

In [4]:
games_encoded = pd.get_dummies(games, columns=['genre','platform'], dtype=int)
display(games_encoded.head())
print('Kolom awal:', len(games.columns))
print('Kolom setelah one-hot encoding:', len(games_encoded.columns))

,game_id,title,release_year,studio,rating,price_usd,sales_millions,review_count,game_age,rating_category,...,genre_Puzzle,genre_RPG,genre_Simulation,genre_Sports,genre_Strategy,platform_Mobile,platform_PC,platform_PlayStation,platform_Switch,platform_Xbox
0,1,Wild Voyage 01,2017,Northstar Studio,6.1,14.99,1.05,1357,9,Medium,...,0,0,0,0,1,0,0,1,0,0
1,2,Amber Islands 02,2025,Blue Comet,6.4,14.99,2.51,15922,1,Medium,...,0,0,0,0,1,0,0,0,1,0
2,3,Amber Frontier 03,2019,Orbit Works,9.1,4.99,6.27,10055,7,High,...,1,0,0,0,0,0,0,0,0,1
3,4,Cosmic Legends 04,2016,Maple Byte,8.3,61.99,2.10,3181,10,High,...,0,0,0,0,0,0,0,0,0,1
4,5,Frost Racers 05,2020,Orbit Works,5.9,9.99,3.10,6481,6,Low,...,0,0,0,0,1,0,0,0,0,1

Kolom awal: 12
Kolom setelah one-hot encoding: 22

## 4. Menyimpan data hasil olahan

In [5]:
output_path = PROJECT_DIR / 'data' / 'games_engineered.csv'
games.to_csv(output_path, index=False)
print('File tersimpan:', output_path)

File tersimpan: d:\smester 5\Exploratory_Data_Analysis_for_Machine_Learning\data\games_engineered.csv

## Tantangan
- Buat kategori harga: Free, Budget (lebih dari 0 sampai 20), Premium (lebih dari 20).
- Hitung rata-rata `sales_millions` untuk setiap `rating_category`.
- Jelaskan mengapa kolom `title` biasanya tidak langsung digunakan sebagai angka dalam model sederhana.